name = "AutomaticMusicTranscription"
uuid = "d36314a0-77c6-484e-b2e7-c3adb10a7433"
authors = ["Eli Smith"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
